services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verifactu-php82
    ports:
    extra_hosts:
      - "telelavo.test:host-gateway"
      - "mitaller.telelavo.test:host-gateway"
    volumes:
      - .:/var/www/html
      - ../.secrets/certs:/run/secrets/verifactu:ro
    restart: unless-stopped
